version: "3.8"

services:
  # Caddy Reverse Proxy
  caddy:
    image: caddy:2.7-alpine
    container_name: waf-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019" # Admin API
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/logs:/var/log/caddy
      - caddy_config:/config
    networks:
      - waf-network
    depends_on:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:2019/config/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Go Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: waf-backend
    restart: unless-stopped
    environment:
      - DB_PATH=/app/data/waf.db
      - CADDY_ADMIN_API=http://caddy:2019
      - LOG_LEVEL=info
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    networks:
      - waf-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Dashboard
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: waf-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - waf-network
    depends_on:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Watchtower for automatic updates (optional)
  watchtower:
    image: containrrr/watchtower:latest
    container_name: waf-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_CLEANUP=true
    networks:
      - waf-network

networks:
  waf-network:
    driver: bridge

volumes:
  caddy_config:
    driver: local
